name: API Tests
on:
  push:
    branches: [ main, master ]
    paths:
      - 'api_tests/**'
      - '.github/workflows/api-tests.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'api_tests/**'
      - '.github/workflows/api-tests.yml'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run API tests
        run: |
          pip install allure-pytest  
          pytest api_tests/ -v --tb=short \
            --html=report.html \
            --self-contained-html \
            --alluredir=./allure-results
        continue-on-error: true

      - name: Upload pytest HTML Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: api-html-test-report
          path: report.html
          retention-days: 30

      - name: Generate Allure Report
        run: |
          npm install -g allure-commandline
          allure generate ./allure-results --clean -o ./allure-report

      - name: Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./allure-report
          destination_dir: allure-report-${{ github.run_number }}

      - name: Comment PR with Allure Report URL
        if: always() && github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '📊 **Allure Report:** https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/allure-report-${{ github.run_number }}'
            })