name: API Tests
on:
  push:
    branches: [ main, master ]
    paths:
      - 'api_tests/**'
      - '.github/workflows/api-tests.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'api_tests/**'
      - '.github/workflows/api-tests.yml'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Allure Report
        run: |
          npm install -g allure-commandline
          allure generate ./allure-results --clean -o ./allure-report

      - name: Create Single HTML Report
        run: |
          # Instalar allure-combine
          npm install -g allure-combine
          allure-combine ./allure-report --dest ./allure-single.html

      - name: Upload Allure Single HTML
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: api-allure-single-report
          path: ./allure-single.html
          retention-days: 30