name: API Tests
on:
  push:
    branches: [ main, master ]
    paths:
      - 'api_tests/**'
      - '.github/workflows/api-tests.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'api_tests/**'
      - '.github/workflows/api-tests.yml'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run API tests
        run: pytest api_tests/ -v --tb=short --html=report.html --self-contained-html
        continue-on-error: true

      - name: Upload test report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: api-test-report
          path: report.html
          retention-days: 30