name: BDD Tests

on:
  push:
    branches: [ main, master ]
    paths:
      - 'behave_tests/**'
      - 'pytest_bdd_tests/**'
      - '.github/workflows/bdd-tests.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'behave_tests/**'
      - 'pytest_bdd_tests/**'
      - '.github/workflows/bdd-tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install ChromeDriver (for Selenium)
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-chromedriver
          echo "/usr/lib/chromium-browser/" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Behave tests
        run: |
          cd behave_tests
          python -m behave features

      - name: Run pytest-bdd tests
        run: |
          pytest pytest_bdd_tests/ -v --tb=short