name: BDD Tests

on:
  push:
    branches: [ main, master ]
    paths:
      - 'behave_tests/**'
      - 'pytest_bdd_tests/**'
      - '.github/workflows/bdd-tests.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'behave_tests/**'
      - 'pytest_bdd_tests/**'
      - '.github/workflows/bdd-tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Behave tests
        run: PYTHONPATH=. behave behave_tests/features
        continue-on-error: true

      - name: Run pytest-bdd tests
        run: pytest pytest_bdd_tests/ -v --tb=short --html=bdd-report.html --self-contained-html
        continue-on-error: true

      - name: Upload test report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: bdd-test-report
          path: bdd-report.html
          retention-days: 30