name: BDD Tests

on:
  push:
    branches: [ main, master ]
    paths:
      - 'features/**'
      - '.github/workflows/bdd-tests.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'features/**'
      - '.github/workflows/bdd-tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run BDD tests
        run: pytest features/ -v --tb=short