name: CI Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  # 🔹 Job 1: Pruebas de API
  api_tests:
    runs-on: ubuntu-latest
    name: Run API Tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run API tests
        run: pytest api_tests/ -v --tb=short

  # 🔹 Job 2: Pruebas BDD (features)
  bdd_tests:
    runs-on: ubuntu-latest
    name: Run BDD Tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run BDD tests
        run: pytest features/ -v --tb=short